/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_camera_jni_campipe */

#ifndef _Included_com_test_camera_jni_campipe
#define _Included_com_test_camera_jni_campipe
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT void JNICALL Java_com_test_camera_jni_campipe_init  
(JNIEnv* pEnv, jobject obj);
JNIEXPORT void JNICALL Java_com_test_camera_jni_campipe_deinit  
(JNIEnv* pEnv, jobject obj);

JNIEXPORT void JNICALL Java_com_test_camera_jni_campipe_sendCmd
  (JNIEnv *pEnv, jobject obj, jbyteArray cmd);

JNIEXPORT jobject JNICALL Java_com_test_camera_jni_campipe_open_1uart
  (JNIEnv *env, jclass thiz, jstring path, jint baudrate, jint flags);

JNIEXPORT void JNICALL Java_com_test_camera_jni_campipe_close_uart
  (JNIEnv *env, jobject thiz);
    
#ifdef __cplusplus
}
#endif
#endif
